name: CI

# Controls when the action will run.
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  gulp:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm i --include=dev
      - run: gulp

      - name: Commit and Push
        run: |
          git config --global user.name 'Gulp Bot'
          git config --global user.email 'booooogulpasugfdhfgjdsg@users.noreply.github.com'
          git add --all
          git commit -am "Update dist folder"
          git push

  cli:
    if: always()
    needs: gulp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm i
      - run: npm i -g node-prune nexe
      - run: node-prune

      - run: mkdir build/
      - run: nexe -t linux-x64-12.16.2 cli.js --resource "./dist/*" -o build/server-linux
      - run: nexe -t windows-x86-12.18.2 cli.js --resource "./dist/*" -o build/server-windows.exe
      - run: nexe -t mac-x64-12.18.2 cli.js --resource "./dist/*" -o build/server-mac

      - uses: edgarrc/action-7z@v1.0.4
        with:
          args: 7z a -t7z -mx=9 build-all.7z ./build/
      - run: zip -9 server-windows.zip build/server-windows.exe
      - run: tar -czf server-mac.tar.gz build/server-mac
      - run: tar -cJf server-linux.tar.xz build/server-linux

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "yeeturl-server"
          files: |
            build-all.7z
            server-windows.zip
            server-mac.tar.gz
            server-linux.tar.xz
