name: Run gulp tasks

# Controls when the action will run.
on:
  push:
    branches: ["master"]
    paths:
    - 'src/**'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job name
  build:
    # Runner name
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up node
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: gulp

      - name: Commit and Push
        run: |
          git config --global user.name 'Gulp Bot'
          git config --global user.email 'booooogulpasugfdhfgjdsg@users.noreply.github.com'
          git add --all
          git commit -am "Update dist folder"
          git push
