name: Run tests (wip)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - run: npm install
    - run: cp env.example .env
    - run: npm start &
    - run: curl 'http://127.0.0.1:3000/api/shorten' --fail -w "%{http_code} --data-raw '{"url":"{\"iv\":\"jiJj/JmAqYHoXmVSZYtJcg==\",\"v\":1,\"iter\":275000,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"salt\":\"gFZxCXCKrQo=\",\"ct\":\"8amN0IkHohOeR9xI4x9i0jr5PIaautKneWDTLTElqdw=\"}"}' --compressed
